version: "3"
services:
    web:
        ports:
            - 8080:80
    server:
        ports:
            - 9230:9230
            - 3333:3333
        environment:
            - DEV=true
    processor:
        ports:
            - 9231:9231
            - 3334:3334
        environment:
            - DEV=true
    mongodb:
        ports:
            - 27017:27017
